import RPi.GPIO as GPIO

# Set GPIO pin numbering
GPIO.setmode(GPIO.BCM)
#setup all GPIO pins
GPIO.setup(1, GPIO.IN)
GPIO.setup(2, GPIO.IN)
GPIO.setup(3, GPIO.IN)
GPIO.setup(4, GPIO.IN)
GPIO.setup(5, GPIO.IN)
GPIO.setup(6, GPIO.IN)
GPIO.setup(7, GPIO.IN)
GPIO.setup(8, GPIO.IN)
GPIO.setup(9, GPIO.IN)
GPIO.setup(10, GPIO.IN)
GPIO.setup(11, GPIO.IN)
GPIO.setup(12, GPIO.IN)
GPIO.setup(13, GPIO.IN)
GPIO.setup(14, GPIO.IN)
GPIO.setup(15, GPIO.IN)
GPIO.setup(16, GPIO.IN)
GPIO.setup(17, GPIO.IN)
GPIO.setup(18, GPIO.IN)
GPIO.setup(19, GPIO.IN)
GPIO.setup(20, GPIO.IN)
GPIO.setup(21, GPIO.IN)
GPIO.setup(22, GPIO.IN)
GPIO.setup(23, GPIO.IN)
GPIO.setup(24, GPIO.IN)
GPIO.setup(25, GPIO.IN)
GPIO.setup(26, GPIO.IN)
GPIO.setup(27, GPIO.IN)
GPIO.setup(28, GPIO.IN)
GPIO.setup(29, GPIO.IN)
GPIO.setup(30, GPIO.IN)
GPIO.setup(31, GPIO.IN)
GPIO.setup(32, GPIO.IN)
GPIO.setup(33, GPIO.IN)
GPIO.setup(34, GPIO.IN)
GPIO.setup(35, GPIO.IN)
GPIO.setup(36, GPIO.IN)
GPIO.setup(37, GPIO.IN)
GPIO.setup(38, GPIO.IN)
GPIO.setup(39, GPIO.IN)
GPIO.setup(40, GPIO.IN)

#print all GPIO values

print('GPIO.input(1)='  + str(GPIO.input(1)))
print('GPIO.input(2)='  + str(GPIO.input(2)))
print('GPIO.input(3)='  + str(GPIO.input(3)))
print('GPIO.input(4)='  + str(GPIO.input(4)))
print('GPIO.input(5)='  + str(GPIO.input(5)))
print('GPIO.input(6)='  + str(GPIO.input(6)))
print('GPIO.input(7)='  + str(GPIO.input(7)))
print('GPIO.input(8)='  + str(GPIO.input(8)))
print('GPIO.input(9)='  + str(GPIO.input(9)))
print('GPIO.input(10)='  + str(GPIO.input(10)))
print('GPIO.input(11)='  + str(GPIO.input(11)))
print('GPIO.input(12)='  + str(GPIO.input(12)))
print('GPIO.input(13)='  + str(GPIO.input(13)))
print('GPIO.input(14)='  + str(GPIO.input(14)))
print('GPIO.input(15)='  + str(GPIO.input(15)))
print('GPIO.input(16)='  + str(GPIO.input(16)))
print('GPIO.input(17)='  + str(GPIO.input(17)))
print('GPIO.input(18)='  + str(GPIO.input(18)))
print('GPIO.input(19)='  + str(GPIO.input(19)))
print('GPIO.input(20)='  + str(GPIO.input(20)))
print('GPIO.input(21)='  + str(GPIO.input(21)))
print('GPIO.input(22)='  + str(GPIO.input(22)))
print('GPIO.input(23)='  + str(GPIO.input(23)))
print('GPIO.input(24)='  + str(GPIO.input(24)))
print('GPIO.input(25)='  + str(GPIO.input(25)))
print('GPIO.input(26)='  + str(GPIO.input(26)))
print('GPIO.input(27)='  + str(GPIO.input(27)))
print('GPIO.input(28)='  + str(GPIO.input(28)))
print('GPIO.input(29)='  + str(GPIO.input(29)))
print('GPIO.input(30)='  + str(GPIO.input(30)))
print('GPIO.input(31)='  + str(GPIO.input(31)))
print('GPIO.input(32)='  + str(GPIO.input(32)))
print('GPIO.input(33)='  + str(GPIO.input(33)))
print('GPIO.input(34)='  + str(GPIO.input(34)))
print('GPIO.input(35)='  + str(GPIO.input(35)))
print('GPIO.input(36)='  + str(GPIO.input(36)))
print('GPIO.input(37)='  + str(GPIO.input(37)))
print('GPIO.input(38)='  + str(GPIO.input(38)))
print('GPIO.input(39)='  + str(GPIO.input(39)))
print('GPIO.input(40)='  + str(GPIO.input(40)))